{% set name = "pyOMA-2" %}
{% set version = "1.2.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyoma_2-{{ version }}.tar.gz
  sha256: 3a62f0ba62b63bbf2a7d015e20d6c98ee068aa99d1112ea4f334abcbc2e8865e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy
    - pandas >=2.0.3
    - scipy >=1.9.3
    - pydantic >=2.5.1
    - tqdm >=4.66.1
    - matplotlib-base >=3.7.4
    - pyvista
    - pyvistaqt
    - pyqt
    - vtk
    - pyqt5-sip
    - openpyxl

test:
  imports:
    - pyoma2
  # # need to commend because pyqt5 in pypi is called pyqt in conda
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyOMA-2/
  summary: Python module for conducting Operational Modal Analysis
  description: |
    pyOMA-2 is a Python module for conducting Operational Modal Analysis.
    For Excel file support, users can additionally install openpyxl>=3.1.3.
  dev_url: https://github.com/dagghe/pyOMA2
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dagghe
    - dfm88
